name: publish-lib

on:
  push:
    branches: [lib]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache node modules
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cacheNodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-cacheNodeModules-

      - name: Install node modules (1)
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Install node modules (2)
        if: ${{ steps.cacheNodeModules.outputs.cache-hit != 'true' }}
        run: npm install --prefix webpack-plugin

      - name: Install Playwright
        run: npm run playwright-install

      - name: Check prettier
        run: npm run prettier-check

      - name: Build
        run: npm run release

      - name: Run unit tests
        run: npm test

      - name: Run smoke test
        run: npm run smoketest

      - name: Publish
        run: |
          git update-index --refresh || true
          if ! git diff-index --quiet HEAD --; then git add release && git commit -m "Automatic build triggered by $GITHUB_SHA" && git push origin lib; fi
